name: messenger
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  shimmer: ^1.1.1
  rxdart: ^0.20.0
  flutter_svg: ^0.19.0
  rxbus: ^0.0.2
  shared_preferences: ^0.5.7+3
  pinput: ^1.0.0
  dotted_border: ^1.0.7
  sqflite: ^1.3.2+2
  flutter_staggered_grid_view: ^0.3.2
  flutter_slidable: ^0.5.7
  image_picker: ^0.6.7+21
  percent_indicator: ^2.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/menu/
    - assets/explore/

  fonts:
    - family: fontNunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
